### ISSUE TITLE
Not working in Atom

### ISSUE THREAD

**Issue by dominicbarnes** [BohdanTkachenko/eslint-plugin-require-path-exists#10]
In Atom, I am getting errors reported about missing modules despite having the right relative path. I've reported the issue AtomLinter/linter-eslint#355.

It turns out that the change made in 3d865400f41e49d3c747df2f55622322d1eed88b (ie: 1.0.24) is what caused this plugin to start breaking. (if I downgrade to 1.0.23, it works in Atom again)

**Comment by Arcanemagus** [comment]
@BohdanTkachenko was there something broken in the environment `linter-eslint` was running `eslint` under that needed this? Was this an attempt to work around the bug fixed [here](https://github.com/AtomLinter/linter-eslint/pull/340)?

Trying to determine if this is something that needs to be fixed here, or over in `linter-eslint`, so far it looks like the fix is here since it seems 1.0.23 works fine.

**Comment by BohdanTkachenko** [comment]
I got the same issue when updated to the latest version of linter-eslint. With the previous version of linter-eslint and latest version of this plugin, everything was fine. I'll try to debug it on the weekend and find out why this happens.

**Comment by Arcanemagus** [comment]
We fixed some environment issues in the PR I linked, it's possible you were trying to work around that in this package and now your workaround is breaking due to it being fixed upstream?

**Comment by BohdanTkachenko** [comment]
@Arcanemagus, yes, I tried to make work around because of bug that you mentioned. I removed this work around in 1.0.25, so now it should work correctly. Thanks for fixing it in linter-eslint package.

Feel free to reopen this issue if any problems still present.
