### ISSUE TITLE
Support for react-native

### ISSUE THREAD

**Issue by theodorton** [BohdanTkachenko/eslint-plugin-require-path-exists#5]
React Native allows file extensions `.android.js` and `.ios.js`. Maybe there could be an option on `require-path-exists/exists` named `extensions` that would accept an array of extra extensions.

There is also support for a special require `require('image!dummy')` that expects some assets to be available in your `images.xcassets` and Android `res`-folder. Might be too specific to include in this plugin.

**Comment by BohdanTkachenko** [comment]
@theodorton, I'm not familiar with react-native, but if you're using webpack there, you can simply add extensions you need to resolve.extensions option (see https://webpack.github.io/docs/configuration.html#resolve-extensions for details). If you're not using webpack there, you can actually create webpack.config.js with this option as a temporary solution. This issue is also related to #3

**Comment by theodorton** [comment]
The `require('image!dummy')`-syntax has changed in React Native, so only the file extension issue needs to be resolved (tracked in #3).

Closing this.
